//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Dep_ID { get; set; }
        public string Dep_Name { get; set; }
        public Nullable<int> Dep_Credit { get; set; }
        public Nullable<int> Dep_CourseID { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
