//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string Stu_ID { get; set; }
        public string Stu_Title { get; set; }
        public string Stu_Name { get; set; }
        public string Stu_Surname { get; set; }
        public bool Stu_Sex { get; set; }
        public System.DateTime Stu_Birthday { get; set; }
        public string Stu_AspEmail { get; set; }
        public string Stu_Tel { get; set; }
        public string Stu_Address { get; set; }
        public string Stu_OldEdu { get; set; }
        public string Stu_OldSchool { get; set; }
        public string Stu_Img { get; set; }
        public string Stu_TeaID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
