//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int Subj_ID { get; set; }
        public string Subj_Code { get; set; }
        public int Subj_DepID { get; set; }
        public string Subj_Name { get; set; }
        public Nullable<int> Subj_Credit { get; set; }
        public Nullable<int> Subj_CoursID { get; set; }
    }
}
