//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Projects = new HashSet<Project>();
            this.Students = new HashSet<Student>();
        }
    
        public string Tea_ID { get; set; }
        public int Tea_TitleID { get; set; }
        public string Tea_Name { get; set; }
        public string Tea_Surname { get; set; }
        public System.DateTime Tea_Birth { get; set; }
        public string Tea_IDCard { get; set; }
        public string Tea_Img { get; set; }
        public string Tea_Export { get; set; }
        public string Tea_LvEdu { get; set; }
        public string Tea_Program { get; set; }
        public string Tea_Faculty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        public virtual Title Title { get; set; }
    }
}
